(() => {
  const rupiah = new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0});
  const qs=(s,r=document)=>r.querySelector(s), qsa=(s,r=document)=>[...r.querySelectorAll(s)];
  const safeJSON=(key,fallback=[])=>{try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch{return fallback}};
  const saveJSON=(key,val)=>localStorage.setItem(key,JSON.stringify(val));
  const escapeHTML=(v='')=>String(v).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const state={balance:Number(localStorage.getItem('ride_wallet_balance')||125000),cart:{},storeType:null};
  const catalogs={
    food:{title:'RIDE Food',subtitle:'Makanan favorit, antar cepat',icon:'🍜',shops:[
      {name:'Nasi Rasa Nusantara',rating:'4.9',eta:'18–25 mnt',badge:'Best seller',items:[{id:'f1',name:'Nasi Ayam Sambal Matah',desc:'Ayam panggang, sambal matah, telur',price:28000,emoji:'🍗'},{id:'f2',name:'Nasi Rendang Komplit',desc:'Rendang sapi, telur, sayur',price:34000,emoji:'🍛'}]},
      {name:'Kopi Tengah Kota',rating:'4.8',eta:'12–20 mnt',badge:'Hemat 20%',items:[{id:'f3',name:'Kopi Susu Aren',desc:'Espresso, susu segar, gula aren',price:22000,emoji:'☕'},{id:'f4',name:'Croissant Butter',desc:'Fresh baked, flaky & buttery',price:25000,emoji:'🥐'}]},
      {name:'Burger District',rating:'4.7',eta:'20–30 mnt',badge:'Popular',items:[{id:'f5',name:'Classic Beef Burger',desc:'Beef patty, cheese, signature sauce',price:39000,emoji:'🍔'},{id:'f6',name:'Loaded Fries',desc:'French fries, beef crumble, cheese',price:27000,emoji:'🍟'}]}
    ]},
    mart:{title:'RIDE Mart',subtitle:'Kebutuhan harian sampai depan pintu',icon:'🛍️',shops:[
      {name:'Quick Daily Market',rating:'4.9',eta:'15–25 mnt',badge:'Buka 24 jam',items:[{id:'m1',name:'Air Mineral 1.5L',desc:'Botol 1.5 liter',price:8000,emoji:'💧'},{id:'m2',name:'Susu Fresh 1L',desc:'Susu segar full cream',price:24000,emoji:'🥛'},{id:'m3',name:'Roti Tawar Premium',desc:'Isi 12 lembar',price:19000,emoji:'🍞'},{id:'m4',name:'Telur Ayam 10 pcs',desc:'Fresh pack',price:26000,emoji:'🥚'}]},
      {name:'Segar Express',rating:'4.8',eta:'18–28 mnt',badge:'Fresh',items:[{id:'m5',name:'Pisang Cavendish',desc:'1 sisir mini',price:29000,emoji:'🍌'},{id:'m6',name:'Apel Fuji',desc:'Pack 4 buah',price:36000,emoji:'🍎'}]}
    ]}
  };

  function toast(msg){const t=qs('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2200)}
  function syncWallet(){localStorage.setItem('ride_wallet_balance',String(state.balance));const b=qs('#walletBalance');if(b)b.textContent=rupiah.format(state.balance).replace(',00','')}
  function addTx(type,amount,label){const tx=safeJSON('ride_wallet_tx');tx.unshift({id:Date.now(),type,amount,label,at:new Date().toISOString()});saveJSON('ride_wallet_tx',tx.slice(0,20))}
  function topup(amount){state.balance+=amount;syncWallet();addTx('in',amount,'Top up demo');toast(`Saldo bertambah ${rupiah.format(amount).replace(',00','')}`);openWallet()}
  function charge(amount,label){if(state.balance<amount)return false;state.balance-=amount;syncWallet();addTx('out',amount,label);return true}

  function mount(){if(!qs('link[data-ride-features]')){const l=document.createElement('link');l.rel='stylesheet';l.href='/features.css';l.dataset.rideFeatures='1';document.head.appendChild(l)}if(!qs('#featureLayer')){const d=document.createElement('div');d.id='featureLayer';d.className='feature-layer';document.body.appendChild(d)}syncWallet();wireCapture();renderCombinedRecent()}
  function openFeature(title,html,subtitle=''){const l=qs('#featureLayer');l.innerHTML=`<div class="feature-backdrop" data-feature-close></div><section class="feature-sheet"><header class="feature-head"><button class="feature-close" data-feature-close>←</button><div><small>${escapeHTML(subtitle)}</small><h2>${escapeHTML(title)}</h2></div><span class="feature-brand">R</span></header><div class="feature-body">${html}</div></section>`;l.classList.add('open');document.body.classList.add('sheet-open');qsa('[data-feature-close]',l).forEach(x=>x.onclick=closeFeature)}
  function closeFeature(){const l=qs('#featureLayer');if(!l)return;l.classList.remove('open');document.body.classList.remove('sheet-open');setTimeout(()=>{if(!l.classList.contains('open'))l.innerHTML=''},220);qsa('[data-nav]').forEach(x=>x.classList.toggle('active',x.dataset.nav==='home'))}

  function allOrders(){return [...safeJSON('ride_orders'),...safeJSON('ride_store_orders')].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt))}
  function renderCombinedRecent(){const root=qs('#recentOrders');if(!root)return;const orders=allOrders();if(!orders.length)return;root.innerHTML=orders.slice(0,3).map(o=>`<div class="order-row"><span class="order-icon">${o.type==='store'?'◒':'↗'}</span><div><b>${escapeHTML(o.service)}</b><small>${new Date(o.createdAt).toLocaleString('id-ID',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})} · ${escapeHTML(o.destination||o.store||'')}</small></div><strong>${rupiah.format(o.fare||o.total||0).replace(',00','')}</strong></div>`).join('')}
  function orderHTML(o){const when=new Date(o.createdAt).toLocaleString('id-ID',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'});return `<article class="full-order"><div class="full-order-icon">${o.type==='store'?'🛍️':'🏍️'}</div><div class="full-order-main"><div class="full-order-top"><b>${escapeHTML(o.service)}</b><span>${escapeHTML(o.status||'Selesai')}</span></div><small>${when}</small><p>${escapeHTML(o.destination||o.store||'')}</p><div><strong>${rupiah.format(o.fare||o.total||0).replace(',00','')}</strong><button data-reorder>Pesan lagi</button></div></div></article>`}
  function openOrders(){const orders=allOrders();openFeature('Pesanan saya',orders.length?`<div class="feature-summary"><div><strong>${orders.length}</strong><span>Total order demo</span></div><div><strong>${rupiah.format(orders.reduce((s,o)=>s+(o.fare||o.total||0),0)).replace(',00','')}</strong><span>Total nilai</span></div></div><div class="full-orders">${orders.map(orderHTML).join('')}</div>`:'<div class="feature-empty"><span>🧾</span><h3>Belum ada pesanan</h3><p>Coba pesan Ride, Food, Mart, atau Send dari beranda.</p></div>','AKTIVITAS');qsa('[data-reorder]',qs('#featureLayer')).forEach(b=>b.onclick=()=>{closeFeature();window.scrollTo({top:0,behavior:'smooth'});toast('Siap membuat pesanan baru.')})}

  function walletTxHTML(tx){return `<div class="wallet-tx"><span class="tx-icon ${tx.type}">${tx.type==='in'?'↓':'↑'}</span><div><b>${escapeHTML(tx.label)}</b><small>${new Date(tx.at).toLocaleString('id-ID',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}</small></div><strong class="${tx.type}">${tx.type==='in'?'+':'-'}${rupiah.format(tx.amount).replace(',00','')}</strong></div>`}
  function openWallet(){const tx=safeJSON('ride_wallet_tx');openFeature('RIDE Wallet',`<div class="wallet-hero"><small>Saldo tersedia</small><h3>${rupiah.format(state.balance).replace(',00','')}</h3><div class="wallet-actions"><button data-topup="50000"><span>＋</span>Top up 50K</button><button data-topup="100000"><span>＋</span>Top up 100K</button><button id="walletTransfer"><span>↗</span>Kirim</button></div></div><div class="feature-section-title"><h3>Transaksi terakhir</h3><span>Demo lokal</span></div><div class="wallet-list">${tx.length?tx.map(walletTxHTML).join(''):'<div class="feature-empty compact"><span>◈</span><p>Belum ada transaksi wallet.</p></div>'}</div><div class="wallet-note"><b>Mode demo</b><p>Saldo ini hanya tersimpan di browser dan tidak mewakili uang sungguhan.</p></div>`,'SALDO & PEMBAYARAN');qsa('[data-topup]',qs('#featureLayer')).forEach(b=>b.onclick=()=>topup(Number(b.dataset.topup)));const t=qs('#walletTransfer');if(t)t.onclick=()=>toast('Transfer antar pengguna membutuhkan backend akun.')}

  function openProfile(){const count=allOrders().length;openFeature('Profil',`<div class="profile-feature"><div class="profile-avatar">CT</div><div><h3>Copy ToLive</h3><p>Member RIDE · akun demo</p></div><button>Ubah</button></div><div class="profile-stats"><div><strong>${count}</strong><span>Pesanan</span></div><div><strong>4.9</strong><span>Rating</span></div><div><strong>2</strong><span>Voucher</span></div></div><div class="settings-list"><button><span>📍</span><div><b>Alamat favorit</b><small>Rumah, kantor, dan tempat tersimpan</small></div><i>›</i></button><button><span>🛡️</span><div><b>Keamanan</b><small>RideSafe dan kontak darurat</small></div><i>›</i></button><button><span>🎟️</span><div><b>Voucher & promo</b><small>2 promo tersedia</small></div><i>›</i></button><button><span>⚙️</span><div><b>Pengaturan</b><small>Bahasa, notifikasi, privasi</small></div><i>›</i></button></div><div class="wallet-note"><b>Status MVP</b><p>Login, verifikasi nomor, dan sinkronisasi akun lintas perangkat membutuhkan backend produksi.</p></div>`,'AKUN SAYA')}

  function cartCount(){return Object.values(state.cart).reduce((n,x)=>n+x.qty,0)}
  function cartTotal(){return Object.values(state.cart).reduce((n,x)=>n+x.qty*x.price,0)}
  function findProduct(type,id){for(const shop of catalogs[type].shops){const item=shop.items.find(x=>x.id===id);if(item)return{...item,store:shop.name}}}
  function storeHTML(type){const cfg=catalogs[type];const shops=cfg.shops.map(shop=>`<section class="merchant"><div class="merchant-head"><div class="merchant-logo">${type==='food'?'🍽️':'🛒'}</div><div><h3>${escapeHTML(shop.name)}</h3><p>★ ${shop.rating} · ${shop.eta}</p></div><span>${escapeHTML(shop.badge)}</span></div><div class="product-grid">${shop.items.map(i=>`<article class="product"><div class="product-art">${i.emoji}</div><div class="product-copy"><h4>${escapeHTML(i.name)}</h4><p>${escapeHTML(i.desc)}</p><div><strong>${rupiah.format(i.price).replace(',00','')}</strong><button data-add="${i.id}">＋</button></div></div></article>`).join('')}</div></section>`).join('');const count=cartCount(),total=cartTotal();return `<div class="store-hero"><div><span>${cfg.icon}</span><div><small>Antar ke</small><b>Lokasi saya</b></div></div><button data-open-wallet>◈ ${rupiah.format(state.balance).replace(',00','')}</button></div><div class="store-search">⌕ <span>Cari ${type==='food'?'makanan atau restoran':'produk kebutuhan harian'}</span></div><div class="store-chips"><button>Terlaris</button><button>Diskon</button><button>Rating 4.5+</button><button>Antar cepat</button></div>${shops}${count?`<div class="cartbar"><div><span>${count} item</span><b>${rupiah.format(total).replace(',00','')}</b></div><button id="checkoutStore">Lihat keranjang →</button></div>`:''}`}
  function wireStore(type){qsa('[data-add]',qs('#featureLayer')).forEach(b=>b.onclick=()=>{const i=findProduct(type,b.dataset.add);if(!i)return;if(!state.cart[i.id])state.cart[i.id]={...i,qty:0};state.cart[i.id].qty++;toast(`${i.name} ditambahkan`);openStore(type)});const c=qs('#checkoutStore');if(c)c.onclick=()=>openCart(type);const w=qs('[data-open-wallet]');if(w)w.onclick=openWallet}
  function openStore(type){state.storeType=type;if(!catalogs[type])return;openFeature(catalogs[type].title,storeHTML(type),catalogs[type].subtitle.toUpperCase());wireStore(type)}
  function openCart(type){const items=Object.values(state.cart),subtotal=cartTotal(),delivery=9000,total=subtotal+delivery;openFeature('Keranjang',items.length?`<div class="cart-store"><span>${catalogs[type].icon}</span><div><small>Pesanan dari</small><b>${escapeHTML(items[0].store||catalogs[type].title)}</b></div></div><div class="cart-items">${items.map(i=>`<div class="cart-item"><span>${i.emoji}</span><div><b>${escapeHTML(i.name)}</b><small>${rupiah.format(i.price).replace(',00','')} × ${i.qty}</small></div><strong>${rupiah.format(i.price*i.qty).replace(',00','')}</strong></div>`).join('')}</div><div class="bill"><div><span>Subtotal</span><b>${rupiah.format(subtotal).replace(',00','')}</b></div><div><span>Biaya antar</span><b>${rupiah.format(delivery).replace(',00','')}</b></div><div class="total"><span>Total</span><b>${rupiah.format(total).replace(',00','')}</b></div></div><div class="pay-card"><span>◈</span><div><small>Bayar dengan</small><b>RIDE Wallet · ${rupiah.format(state.balance).replace(',00','')}</b></div></div><button class="feature-primary" id="placeStoreOrder">Pesan sekarang · ${rupiah.format(total).replace(',00','')}</button><button class="feature-link" id="backToStore">← Tambah item lagi</button>`:'<div class="feature-empty"><span>🛒</span><h3>Keranjang kosong</h3><p>Tambahkan item terlebih dahulu.</p></div>','CHECKOUT');const b=qs('#backToStore');if(b)b.onclick=()=>openStore(type);const p=qs('#placeStoreOrder');if(p)p.onclick=()=>placeStoreOrder(type,total)}
  function placeStoreOrder(type,total){if(state.balance<total){toast('Saldo tidak cukup. Top up demo dulu.');openWallet();return}charge(total,catalogs[type].title);const items=Object.values(state.cart),orders=safeJSON('ride_store_orders');orders.unshift({id:Date.now(),type:'store',service:catalogs[type].title,store:items[0]?.store||catalogs[type].title,total,status:'Sedang diproses',createdAt:new Date().toISOString(),items:items.map(i=>({name:i.name,qty:i.qty}))});saveJSON('ride_store_orders',orders.slice(0,12));state.cart={};renderCombinedRecent();openFeature('Pesanan diterima',`<div class="success-state"><div>✓</div><h3>Pesanan sedang disiapkan</h3><p>Merchant sudah menerima order demo kamu. Estimasi tiba 20–30 menit.</p><strong>${rupiah.format(total).replace(',00','')}</strong><button class="feature-primary" id="successOrders">Lihat pesanan</button><button class="feature-link" data-feature-close>Kembali ke beranda</button></div>`,'ORDER BERHASIL');const s=qs('#successOrders');if(s)s.onclick=openOrders;qsa('[data-feature-close]',qs('#featureLayer')).forEach(x=>x.onclick=closeFeature)}

  function openMore(){openFeature('Semua layanan',`<div class="all-services"><button data-pick="ride"><span>🏍️</span><b>Ride</b><small>Motor</small></button><button data-pick="car"><span>🚗</span><b>Car</b><small>Mobil</small></button><button data-store="food"><span>🍜</span><b>Food</b><small>Makanan</small></button><button data-pick="send"><span>📦</span><b>Send</b><small>Paket</small></button><button data-store="mart"><span>🛍️</span><b>Mart</b><small>Belanja</small></button><button data-wallet><span>◈</span><b>Wallet</b><small>Bayar</small></button><button data-soon="Health"><span>✚</span><b>Health</b><small>Segera</small></button><button data-soon="Tickets"><span>🎫</span><b>Tickets</b><small>Segera</small></button></div>`,'SUPER APP');qsa('[data-store]',qs('#featureLayer')).forEach(b=>b.onclick=()=>openStore(b.dataset.store));qsa('[data-wallet]',qs('#featureLayer')).forEach(b=>b.onclick=openWallet);qsa('[data-soon]',qs('#featureLayer')).forEach(b=>b.onclick=()=>toast(`RIDE ${b.dataset.soon} akan hadir pada fase berikutnya.`));qsa('[data-pick]',qs('#featureLayer')).forEach(b=>b.onclick=()=>{closeFeature();const target=qs(`[data-service="${b.dataset.pick}"]`);if(target)target.click()})}
  function openNotifications(){openFeature('Notifikasi',`<div class="notification-list"><article><span>🎉</span><div><b>Selamat datang di RIDE</b><p>Gunakan kode RIDENOW untuk promo perjalanan demo pertama.</p><small>Baru saja</small></div></article><article><span>🛡️</span><div><b>RideSafe aktif</b><p>Fitur keselamatan tersedia di setiap perjalanan.</p><small>Hari ini</small></div></article></div>`,'PUSAT INFO')}

  function intercept(el,handler){if(!el)return;el.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();handler(e)},true)}
  function wireCapture(){qsa('.service-card').forEach(btn=>{if(['food','mart','more'].includes(btn.dataset.service))intercept(btn,()=>btn.dataset.service==='more'?openMore():openStore(btn.dataset.service))});qsa('[data-nav]').forEach(btn=>{if(btn.dataset.nav!=='home')intercept(btn,()=>{qsa('[data-nav]').forEach(x=>x.classList.toggle('active',x===btn));if(btn.dataset.nav==='orders')openOrders();if(btn.dataset.nav==='wallet')openWallet();if(btn.dataset.nav==='profile')openProfile()})});intercept(qs('#walletButton'),openWallet);intercept(qs('#profileButton'),openProfile);intercept(qs('#notificationButton'),openNotifications);intercept(qs('#changePayment'),openWallet);intercept(qs('#viewAllOrders'),openOrders)}
  window.RIDE2={openOrders,openWallet,openProfile,openStore,openMore,toast};
  mount();
})();