(() => {
  'use strict';
  const qs=(s,r=document)=>r.querySelector(s), qsa=(s,r=document)=>[...r.querySelectorAll(s)];
  const money=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n||0)).replace(',00','');
  const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const read=(k,d=[])=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}}, write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  const groups={all:'Semua',transport:'Transport & Logistik',shopping:'Food & Shopping',finance:'Keuangan',benefits:'Benefits & Safety',business:'Bisnis'};
  const services=[
    ['ride','transport','🏍️','RIDE Motor','Motor cepat','green'],['car','transport','🚗','RIDE Car','Mobil nyaman','blue'],['carplus','transport','✨','RIDE Premium','Mobil pilihan','navy'],['send','transport','📦','RIDE Send','Kirim instan','orange'],['box','transport','🚚','RIDE Box','Barang besar','brown'],['transit','transport','🚆','RIDE Transit','Ride + kereta','red'],['schedule','transport','🗓️','Jadwal','Pesan nanti','purple'],
    ['food','shopping','🍜','RIDE Food','Pesan makanan','red'],['mart','shopping','🛒','RIDE Mart','Belanja harian','green'],['shop','shopping','🛍️','RIDE Shop','Titip beli apa saja','pink'],
    ['wallet','finance','◈','RIDE Wallet','Saldo & transaksi','navy'],['pay','finance','▦','Bayar QR','Scan & bayar','blue'],['topup','finance','＋','Top Up','Isi saldo','green'],['transfer','finance','↗','Transfer','Kirim uang','cyan'],['request','finance','↙','Minta Uang','Buat permintaan','purple'],['pulsa','finance','📱','Pulsa & Data','Isi nomor HP','orange'],['bills','finance','🧾','Tagihan','PLN, air, internet','blue'],
    ['plus','benefits','★','RIDE Plus','Langganan hemat','purple'],['rewards','benefits','🎁','Rewards','Poin & hadiah','orange'],['promo','benefits','🎟️','Promo','Voucher aktif','red'],['safety','benefits','🛡️','Safety Center','Perlindungan trip','green'],['help','benefits','?','Pusat Bantuan','Bantuan 24/7','navy'],
    ['corporate','business','🏢','RIDE Corporate','Biaya perusahaan','navy'],['merchant','business','🏪','RIDE Merchant','Kelola usaha','green'],['driver','business','🪪','Mitra Driver','Daftar & pendapatan','orange'],['pos','business','🧮','RIDE POS','Kasir & laporan','blue'],['ads','business','📣','RIDE Ads','Promosikan usaha','pink']
  ].map(x=>({id:x[0],group:x[1],icon:x[2],title:x[3],desc:x[4],tone:x[5]}));
  const balance=()=>Number(localStorage.getItem('ride_wallet_balance')||125000);
  function setBalance(v){v=Math.max(0,Math.round(Number(v)||0));localStorage.setItem('ride_wallet_balance',String(v));['#walletBalance','#superBalance'].forEach(s=>{const e=qs(s);if(e)e.textContent=money(v)});window.RIDE2?.setBalance?.(v);return v}
  function toast(m){if(window.RIDE2?.toast)return window.RIDE2.toast(m);const e=qs('#toast');if(!e)return;e.textContent=m;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2200)}
  function tx(type,amount,label){const a=read('ride_wallet_tx');a.unshift({id:Date.now(),type,amount,label,at:new Date().toISOString()});write('ride_wallet_tx',a.slice(0,40))}
  function order(service,total,label,status='Diproses',extra={}){const a=read('ride_service_orders');a.unshift({id:Date.now(),type:'service',service,total,fare:total,destination:label,status,createdAt:new Date().toISOString(),...extra});write('ride_service_orders',a.slice(0,30));window.RIDE2?.renderCombinedRecent?.()}
  function charge(amount,label){if(balance()<amount){openSheet('Saldo belum cukup','RIDE WALLET',`<div class="result-state warning"><div class="result-icon">◈</div><h3>Butuh ${money(amount)}</h3><p>Saldo saat ini ${money(balance())}. Tambahkan saldo demo untuk melanjutkan.</p><button class="super-primary" data-super-service="topup">Top up sekarang</button></div>`);return false}setBalance(balance()-amount);tx('out',amount,label);return true}
  function openSheet(title,sub,html){const l=qs('#superLayer');if(!l)return;l.innerHTML=`<div class="super-backdrop" data-super-close></div><section class="super-sheet"><header class="super-head"><button class="super-back" data-super-close>←</button><div><small>${esc(sub)}</small><h2>${esc(title)}</h2></div><span class="super-logo">R</span></header><div class="super-body">${html}</div></section>`;l.classList.add('open');document.body.classList.add('super-open')}
  function closeSheet(){const l=qs('#superLayer');if(!l)return;l.classList.remove('open');document.body.classList.remove('super-open');setTimeout(()=>{if(!l.classList.contains('open'))l.innerHTML=''},220)}
  function success(title,text,sub='RIDE'){openSheet(title,sub,`<div class="result-state success"><div class="result-icon">✓</div><h3>${esc(title)}</h3><p>${esc(text)}</p><button class="super-primary" id="successOrders">Lihat pesanan</button><button class="super-link" data-super-close>Kembali ke beranda</button></div>`)}
  function renderHub(group='all',query=''){const r=qs('#serviceCatalog');if(!r)return;const q=query.toLowerCase().trim();const list=services.filter(s=>(group==='all'||s.group===group)&&(!q||`${s.title} ${s.desc} ${groups[s.group]}`.toLowerCase().includes(q)));r.innerHTML=list.map(s=>`<button class="super-service-card" data-super-service="${s.id}"><span class="super-service-icon tone-${s.tone}">${s.icon}</span><span><b>${esc(s.title)}</b><small>${esc(s.desc)}</small></span></button>`).join('')||'<div class="service-no-result">Tidak ada layanan yang cocok.</div>'}
  function existing(id){closeSheet();qs(`[data-service="${id}"]`)?.click();setTimeout(()=>qs('.booking-layout')?.scrollIntoView({behavior:'smooth',block:'start'}),70)}
  function wallet(){const rows=read('ride_wallet_tx').slice(0,10).map(t=>`<div class="super-tx"><span class="${t.type}">${t.type==='in'?'↓':'↑'}</span><div><b>${esc(t.label)}</b><small>${new Date(t.at).toLocaleString('id-ID',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}</small></div><strong>${t.type==='in'?'+':'-'}${money(t.amount)}</strong></div>`).join('');openSheet('RIDE Wallet','DOMPET DIGITAL',`<div class="super-wallet-card"><small>Saldo tersedia</small><h3>${money(balance())}</h3><div class="super-wallet-actions"><button data-super-service="pay"><span>▦</span>Bayar</button><button data-super-service="topup"><span>＋</span>Top Up</button><button data-super-service="transfer"><span>↗</span>Transfer</button><button data-super-service="request"><span>↙</span>Minta</button></div></div><div class="mini-service-grid"><button data-super-service="pulsa"><span>📱</span><b>Pulsa</b></button><button data-super-service="bills"><span>🧾</span><b>Tagihan</b></button><button data-super-service="rewards"><span>🎁</span><b>Rewards</b></button><button data-super-service="promo"><span>🎟️</span><b>Promo</b></button></div><div class="super-section-title"><h3>Aktivitas wallet</h3><span>Demo lokal</span></div><div>${rows||'<div class="super-empty">Belum ada transaksi wallet.</div>'}</div>`)}
  function topup(){openSheet('Top up saldo','RIDE WALLET',`<div class="flow-card"><label>Nominal top up</label><div class="amount-grid">${[20000,50000,100000,200000,500000,1000000].map(v=>`<button data-topup-amount="${v}">${money(v)}</button>`).join('')}</div><label>Nominal lain</label><div class="input-money"><span>Rp</span><input id="customTopup" inputmode="numeric" placeholder="Masukkan nominal"></div><button class="super-primary" id="doTopup">Tambahkan saldo demo</button></div><div class="info-note"><b>Mode demo</b><p>Tidak ada uang sungguhan yang diproses.</p></div>`)}
  function pay(){openSheet('Bayar dengan QR','RIDE PAY',`<div class="qr-scanner"><div class="qr-corners"><div class="fake-qr">▦</div></div><b>Arahkan kamera ke QR merchant</b><p>Atau gunakan simulasi pembayaran manual.</p></div><div class="flow-card"><label>Merchant</label><input id="payMerchant" value="RIDE Merchant Demo"><label>Nominal</label><div class="input-money"><span>Rp</span><input id="payAmount" inputmode="numeric" value="25000"></div><button class="super-primary" id="doPay">Bayar ${money(25000)}</button></div>`)}
  function transfer(){openSheet('Transfer uang','RIDE WALLET',`<div class="flow-card"><label>Nomor HP / ID penerima</label><input id="transferTo" placeholder="08xxxxxxxxxx"><label>Nominal</label><div class="input-money"><span>Rp</span><input id="transferAmount" inputmode="numeric" placeholder="0"></div><div class="quick-amounts">${[20000,50000,100000].map(v=>`<button data-fill-amount="${v}">${money(v)}</button>`).join('')}</div><label>Catatan</label><input id="transferNote" placeholder="Opsional"><button class="super-primary" id="doTransfer">Lanjut transfer</button></div>`)}
  function requestMoney(){openSheet('Minta uang','RIDE WALLET',`<div class="flow-card"><label>Nominal permintaan</label><div class="input-money"><span>Rp</span><input id="requestAmount" inputmode="numeric" value="50000"></div><label>Catatan</label><input id="requestNote" placeholder="Patungan makan, tiket, dll"><button class="super-primary" id="doRequest">Buat permintaan</button></div>`)}
  function pulsa(){openSheet('Pulsa & paket data','RIDE DIGITAL',`<div class="flow-card"><label>Nomor HP</label><input id="phoneNumber" inputmode="tel" placeholder="08xxxxxxxxxx"><label>Pilih produk</label><div class="product-choice">${[['Pulsa 25K',27000],['Pulsa 50K',52000],['Pulsa 100K',102000],['Data 8 GB',45000],['Data 15 GB',65000],['Data 30 GB',99000]].map(([n,p])=>`<button data-digital-name="${n}" data-digital-price="${p}"><b>${n}</b><span>${money(p)}</span></button>`).join('')}</div></div>`)}
  function bills(){openSheet('Bayar tagihan','RIDE TAGIHAN',`<div class="bill-categories">${[['⚡','Listrik'],['💧','Air'],['🌐','Internet'],['🏠','PBB'],['🏥','BPJS'],['📺','TV Kabel']].map(([i,n])=>`<button data-bill-type="${n}"><span>${i}</span><b>${n}</b></button>`).join('')}</div><div class="flow-card"><label>Jenis tagihan</label><input id="billType" value="Listrik" readonly><label>Nomor pelanggan</label><input id="billCustomer" placeholder="ID pelanggan"><label>Nominal simulasi</label><div class="input-money"><span>Rp</span><input id="billAmount" value="175000" inputmode="numeric"></div><button class="super-primary" id="doBill">Bayar tagihan</button></div>`)}
  function transit(){openSheet('RIDE Transit','TRANSPORTASI PUBLIK',`<div class="transit-hero"><span>🚆</span><div><b>Satu perjalanan, beberapa moda</b><p>Kombinasikan Ride/Car ke stasiun, tiket kereta, lalu perjalanan lanjutan.</p></div></div><div class="flow-card"><label>Dari</label><select id="transitFrom"><option>Stasiun Jakarta Kota</option><option>Stasiun Manggarai</option><option>Stasiun Sudirman</option><option>Stasiun Depok Baru</option></select><label>Tujuan</label><select id="transitTo"><option>Stasiun Bogor</option><option>Stasiun Depok Baru</option><option>Stasiun Tanah Abang</option><option>Stasiun Bekasi</option></select><div class="transit-options"><button class="selected" data-transit-price="18000"><b>Hemat</b><span>Ride + Kereta</span><strong>${money(18000)}</strong></button><button data-transit-price="31000"><b>Nyaman</b><span>Car + Kereta</span><strong>${money(31000)}</strong></button></div><button class="super-primary" id="buyTransit" data-price="18000">Pesan perjalanan · ${money(18000)}</button></div>`)}
  function box(){openSheet('RIDE Box','LOGISTIK BESAR',`<div class="flow-card"><label>Alamat jemput</label><input id="boxPickup" placeholder="Gudang / alamat jemput"><label>Alamat tujuan</label><input id="boxDest" placeholder="Alamat tujuan"><label>Pilih kendaraan</label><div class="truck-options">${[['🛻','Pickup','Hingga 1 ton',85000],['🚚','Engkel','Hingga 2 ton',150000],['🚛','Box Besar','Hingga 4 ton',240000]].map((x,i)=>`<button ${i?'':'class="selected"'} data-truck="${x[1]}" data-truck-price="${x[3]}"><span>${x[0]}</span><div><b>${x[1]}</b><small>${x[2]}</small></div><strong>${money(x[3])}</strong></button>`).join('')}</div><button class="super-primary" id="bookBox" data-price="85000" data-truck="Pickup">Pesan Pickup · ${money(85000)}</button></div>`)}
  function shop(){openSheet('RIDE Shop','TITIP BELI',`<div class="flow-card"><label>Apa yang ingin dibeli?</label><textarea id="shopItems" rows="4" placeholder="Contoh: kabel USB-C, baterai AA"></textarea><label>Toko</label><input id="shopStore" placeholder="Nama / lokasi toko"><label>Budget barang</label><div class="input-money"><span>Rp</span><input id="shopBudget" value="100000" inputmode="numeric"></div><div class="cost-preview"><span>Biaya jasa & antar demo</span><b>${money(18000)}</b></div><button class="super-primary" id="bookShop">Cari shopper · ${money(18000)}</button></div>`)}
  function schedule(){const d=new Date(Date.now()+3600000),iso=new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);openSheet('Jadwalkan perjalanan','RIDE RESERVE',`<div class="flow-card"><label>Tanggal & waktu</label><input id="scheduleTime" type="datetime-local" value="${iso}"><label>Kendaraan</label><select id="scheduleType"><option>RIDE Motor</option><option>RIDE Car</option><option>RIDE Premium</option></select><label>Tujuan</label><input id="scheduleDest" placeholder="Masukkan tujuan"><div class="cost-preview"><span>Biaya reservasi demo</span><b>${money(5000)}</b></div><button class="super-primary" id="doSchedule">Simpan jadwal</button></div>`)}
  function premium(){openSheet('RIDE Premium','TRANSPORT EKSEKUTIF',`<div class="premium-banner"><span>✨</span><div><h3>Perjalanan lebih premium</h3><p>Driver berperingkat tinggi, kendaraan pilihan, dan dukungan prioritas.</p></div></div><div class="premium-list"><div><span>🚘</span><div><b>Premium Sedan</b><small>1–3 penumpang</small></div></div><div><span>🚙</span><div><b>Premium XL</b><small>Hingga 6 penumpang</small></div></div><div><span>🛡️</span><div><b>Priority Support</b><small>Bantuan perjalanan prioritas</small></div></div></div><button class="super-primary" id="choosePremium">Pilih RIDE Car Premium</button>`)}
  function plus(){const active=localStorage.getItem('ride_plus_active')==='1';openSheet('RIDE Plus','LANGGANAN',`<div class="plus-hero"><span>★</span><div><small>${active?'AKTIF':'MEMBERSHIP'}</small><h3>${active?'RIDE Plus kamu aktif':'Lebih hemat setiap hari'}</h3><p>Benefit ongkir, perjalanan, makanan, dan belanja.</p></div></div><div class="benefit-list"><div><span>✓</span><p><b>Diskon perjalanan</b><small>Potongan sampai 10%.</small></p></div><div><span>✓</span><p><b>Gratis biaya antar</b><small>Kuota benefit Food & Mart.</small></p></div><div><span>✓</span><p><b>Prioritas promo</b><small>Akses voucher khusus member.</small></p></div></div>${active?'<button class="super-secondary" id="managePlus">Kelola langganan</button>':`<div class="plan-grid"><button class="selected" data-plan="Bulanan" data-plan-price="29000"><b>Bulanan</b><strong>${money(29000)}</strong><small>/bulan</small></button><button data-plan="Tahunan" data-plan-price="249000"><b>Tahunan</b><strong>${money(249000)}</strong><small>hemat 28%</small></button></div><button class="super-primary" id="subscribePlus" data-plan="Bulanan" data-price="29000">Aktifkan Plus · ${money(29000)}</button>`}`)}
  function rewards(){const pts=Number(localStorage.getItem('ride_points')||1250);openSheet('RIDE Rewards','LOYALTY',`<div class="points-card"><small>Poin tersedia</small><h3>${pts.toLocaleString('id-ID')} pts</h3><p>Tukar poin untuk benefit demo.</p></div><div class="reward-list">${[['🏍️','Voucher Ride 10K',250],['🍜','Gratis Antar Food',400],['◈','Cashback 20K',600]].map(x=>`<button data-reward="${x[1]}" data-reward-cost="${x[2]}"><span>${x[0]}</span><div><b>${x[1]}</b><small>${x[2]} pts</small></div><strong>Tukar</strong></button>`).join('')}</div>`)}
  function promo(){const extra=read('ride_promos').map(p=>({name:p.code,title:p.name,desc:'Reward voucher',tone:'purple'}));const list=[{name:'RIDENOW',title:'Diskon 25% perjalanan',desc:'Maks. Rp15.000',tone:'green'},{name:'MAKANHEMAT',title:'Food hemat Rp20.000',desc:'Min. transaksi Rp75.000',tone:'red'},{name:'MART10',title:'Diskon Mart 10%',desc:'Maks. Rp12.000',tone:'blue'},...extra];openSheet('Promo & voucher','RIDE DEALS',`<div class="voucher-list">${list.map(p=>`<article class="voucher tone-${p.tone}"><div><small>KODE ${esc(p.name)}</small><h3>${esc(p.title)}</h3><p>${esc(p.desc)}</p></div><button data-copy-text="${esc(p.name)}">Salin</button></article>`).join('')}</div>`)}
  function safety(){openSheet('Safety Center','PERLINDUNGAN',`<div class="safety-status"><span>🛡️</span><div><b>RideSafe aktif</b><p>Fitur keselamatan untuk perjalanan RIDE.</p></div><strong>ON</strong></div><div class="safety-grid"><button id="shareTrip"><span>📍</span><b>Bagikan perjalanan</b><small>Kirim status trip</small></button><button id="emergencyHelp"><span>☎</span><b>Bantuan darurat</b><small>Akses cepat</small></button><button id="audioProtect"><span>🎙️</span><b>Rekam audio</b><small>Proteksi trip</small></button><button id="insuranceInfo"><span>☂</span><b>Perlindungan</b><small>Info proteksi</small></button></div><div class="flow-card"><label>Kontak tepercaya</label><input id="safetyContact" value="${esc(localStorage.getItem('ride_safety_contact')||'')}" placeholder="Nama / nomor telepon"><button class="super-secondary" id="saveSafetyContact">Simpan kontak</button></div>`)}
  function help(){const f=[['Pesanan & perjalanan','Titik jemput, pembatalan, status pesanan.'],['Pembayaran & wallet','Top up, transfer, refund, transaksi.'],['Food, Mart & Shop','Merchant, stok, pengiriman.'],['Akun & keamanan','Nomor HP, PIN, privasi.'],['Mitra & bisnis','Driver, merchant, corporate, POS.']];openSheet('Pusat Bantuan','SUPPORT 24/7',`<div class="help-search">⌕ <input placeholder="Cari topik bantuan"></div><div class="faq-list">${f.map(x=>`<button><div><b>${x[0]}</b><small>${x[1]}</small></div><span>›</span></button>`).join('')}</div><div class="support-card"><span>💬</span><div><b>Butuh bantuan lain?</b><p>Chat support demo tersedia.</p></div><button id="openSupportChat">Chat</button></div>`)}
  function corporate(){openSheet('RIDE Corporate','BUSINESS EXPENSE',`<div class="business-hero"><small>BULAN INI</small><h3>${money(12845000)}</h3><p>Pengeluaran mobilitas & layanan perusahaan</p></div><div class="metric-grid"><div><b>184</b><span>Perjalanan</span></div><div><b>42</b><span>Karyawan</span></div><div><b>96%</b><span>Dalam policy</span></div></div>${bizActions([['👥','Karyawan','Tambah dan kelola akses'],['⚙️','Limit & aturan','Atur budget dan alasan'],['🎟️','Voucher perusahaan','Buat kode untuk tim'],['📊','Laporan','Ringkasan biaya']])}`)}
  function bizActions(a){return `<div class="business-actions">${a.map(x=>`<button><span>${x[0]}</span><div><b>${x[1]}</b><small>${x[2]}</small></div><i>›</i></button>`).join('')}</div>`}
  function merchant(){openSheet('RIDE Merchant','MITRA USAHA',`<div class="merchant-dashboard"><div><small>Penjualan hari ini</small><h3>${money(2475000)}</h3><span>+14.8% vs kemarin</span></div><div class="merchant-mini"><b>38</b><span>Order</span><b>4.9</b><span>Rating</span></div></div>${bizActions([['🍜','Kelola menu','Produk, stok, harga'],['🏷️','Promo','Diskon dan campaign'],['🧮','RIDE POS','Kasir dan laporan'],['📣','RIDE Ads','Tingkatkan jangkauan']])}<button class="super-secondary" id="merchantOnboarding">Daftarkan usaha baru</button>`)}
  function driver(){openSheet('Mitra Driver','PARTNER CENTER',`<div class="driver-hero"><div class="driver-big-icon">🏍️</div><div><small>PENDAPATAN HARI INI</small><h3>${money(286500)}</h3><p>8 perjalanan · 6 jam online</p></div></div><div class="metric-grid"><div><b>4.96</b><span>Rating</span></div><div><b>98%</b><span>Completion</span></div><div><b>12</b><span>Poin</span></div></div>${bizActions([['▶','Mulai online','Terima permintaan'],['💰','Pendapatan','Riwayat & insentif'],['🛡️','Safety partner','Proteksi dan bantuan']])}<button class="super-secondary" id="driverOnboarding">Daftar sebagai mitra baru</button>`)}
  function pos(){openSheet('RIDE POS','POINT OF SALE',`<div class="pos-display"><div><small>Total transaksi</small><h3>${money(0)}</h3></div><button id="posClear">Hapus</button></div><div class="pos-items">${[['Kopi Susu',22000],['Nasi Ayam',32000],['Roti',18000],['Es Teh',10000]].map(x=>`<button data-pos-item="${x[0]}" data-pos-price="${x[1]}"><b>${x[0]}</b><span>${money(x[1])}</span></button>`).join('')}</div><button class="super-primary" id="posCharge">Buat transaksi kasir</button>`)}
  function ads(){openSheet('RIDE Ads','BUSINESS GROWTH',`<div class="flow-card"><label>Nama campaign</label><input id="adsName" value="Promo Akhir Pekan"><label>Tujuan</label><select><option>Tambah order</option><option>Jangkauan brand</option><option>Promosi menu baru</option></select><label>Budget harian</label><div class="input-money"><span>Rp</span><input value="100000" inputmode="numeric"></div><div class="ad-preview"><small>ESTIMASI</small><h3>2.400–3.800</h3><p>tayangan / hari pada mode demo.</p></div><button class="super-primary" id="launchAds">Aktifkan campaign demo</button></div>`)}
  function allServices(){openSheet('Semua layanan','RIDE SUPER APP',`<div class="sheet-search"><span>⌕</span><input id="sheetServiceSearch" placeholder="Cari layanan RIDE"></div>${Object.entries(groups).filter(x=>x[0]!=='all').map(([k,v])=>`<section class="sheet-service-group"><h3>${v}</h3><div class="sheet-service-grid">${services.filter(s=>s.group===k).map(s=>`<button data-super-service="${s.id}"><span class="super-service-icon tone-${s.tone}">${s.icon}</span><b>${esc(s.title.replace('RIDE ',''))}</b></button>`).join('')}</div></section>`).join('')}`)}
  const open={wallet,pay,topup,transfer,request:requestMoney,pulsa,bills,transit,box,shop,schedule,carplus:premium,plus,rewards,promo,safety,help,corporate,merchant,driver,pos,ads,all:allServices};
  function service(id){if(['ride','car','send'].includes(id))return existing(id);if(['food','mart'].includes(id))return window.RIDE2?.openStore?.(id);return (open[id]||allServices)()}
  function sync(){setBalance(balance());const p=qs('#homePoints');if(p)p.textContent=`${Number(localStorage.getItem('ride_points')||1250).toLocaleString('id-ID')} pts`;const s=qs('#plusStatus');if(s)s.textContent=localStorage.getItem('ride_plus_active')==='1'?'Aktif':'Coba sekarang'}
  function mount(){if(!qs('#superLayer')){const l=document.createElement('div');l.id='superLayer';l.className='super-layer';document.body.appendChild(l)}renderHub();sync();
    document.addEventListener('click',e=>{const c=e.target.closest('[data-super-close]');if(c){e.preventDefault();closeSheet();return}const svc=e.target.closest('[data-super-service]');if(svc){e.preventDefault();e.stopPropagation();service(svc.dataset.superService);return}const more=e.target.closest('.service-card[data-service="more"]');if(more){e.preventDefault();e.stopImmediatePropagation();allServices();return}const w=e.target.closest('#walletButton,[data-nav="wallet"]');if(w){e.preventDefault();e.stopImmediatePropagation();wallet();return}
      const ta=e.target.closest('[data-topup-amount]');if(ta){qsa('[data-topup-amount]').forEach(x=>x.classList.toggle('selected',x===ta));if(qs('#customTopup'))qs('#customTopup').value=ta.dataset.topupAmount;return}const fa=e.target.closest('[data-fill-amount]');if(fa){if(qs('#transferAmount'))qs('#transferAmount').value=fa.dataset.fillAmount;return}
      const dig=e.target.closest('[data-digital-name]');if(dig){const phone=qs('#phoneNumber')?.value.trim();const price=Number(dig.dataset.digitalPrice);if(!phone||phone.length<8)return toast('Masukkan nomor HP.');if(charge(price,`${dig.dataset.digitalName} · ${phone}`)){order('RIDE Pulsa',price,`${dig.dataset.digitalName} · ${phone}`,'Berhasil');success('Pembelian berhasil',`${dig.dataset.digitalName} untuk ${phone} sedang diproses.`,'PULSA & DATA')}return}
      const bt=e.target.closest('[data-bill-type]');if(bt&&qs('#billType')){qs('#billType').value=bt.dataset.billType;return}const tr=e.target.closest('[data-transit-price]');if(tr){qsa('[data-transit-price]').forEach(x=>x.classList.toggle('selected',x===tr));const b=qs('#buyTransit');if(b){b.dataset.price=tr.dataset.transitPrice;b.textContent=`Pesan perjalanan · ${money(tr.dataset.transitPrice)}`}return}const tk=e.target.closest('[data-truck-price]');if(tk){qsa('[data-truck-price]').forEach(x=>x.classList.toggle('selected',x===tk));const b=qs('#bookBox');if(b){b.dataset.price=tk.dataset.truckPrice;b.dataset.truck=tk.dataset.truck;b.textContent=`Pesan ${tk.dataset.truck} · ${money(tk.dataset.truckPrice)}`}return}const pl=e.target.closest('[data-plan-price]');if(pl){qsa('[data-plan-price]').forEach(x=>x.classList.toggle('selected',x===pl));const b=qs('#subscribePlus');if(b){b.dataset.price=pl.dataset.planPrice;b.dataset.plan=pl.dataset.plan;b.textContent=`Aktifkan Plus · ${money(pl.dataset.planPrice)}`}return}
      const rw=e.target.closest('[data-reward-cost]');if(rw){const pts=Number(localStorage.getItem('ride_points')||1250),cost=Number(rw.dataset.rewardCost);if(pts<cost)return toast('Poin belum cukup.');localStorage.setItem('ride_points',String(pts-cost));const pr=read('ride_promos');pr.unshift({name:rw.dataset.reward,code:`RWD${Math.random().toString(36).slice(2,6).toUpperCase()}`});write('ride_promos',pr);toast('Reward berhasil ditukar.');return rewards()}const cp=e.target.closest('[data-copy-text]');if(cp){navigator.clipboard?.writeText(cp.dataset.copyText).catch(()=>{});return toast(`Kode ${cp.dataset.copyText} disalin.`)}const pi=e.target.closest('[data-pos-item]');if(pi){const b=qs('#posCharge'),v=Number(b?.dataset.total||0)+Number(pi.dataset.posPrice);if(b)b.dataset.total=String(v);if(qs('.pos-display h3'))qs('.pos-display h3').textContent=money(v);return toast(`${pi.dataset.posItem} ditambahkan.`)}
      if(e.target.closest('#doTopup')){const n=Number(qs('#customTopup')?.value||0);if(n<10000)return toast('Minimum Rp10.000.');setBalance(balance()+n);tx('in',n,'Top up demo');return success('Top up berhasil',`${money(n)} ditambahkan. Saldo baru ${money(balance())}.`,'RIDE WALLET')}
      if(e.target.closest('#doPay')){const m=qs('#payMerchant')?.value.trim()||'Merchant',a=Number(qs('#payAmount')?.value||0);if(a<1000)return toast('Masukkan nominal.');if(charge(a,`Bayar QR · ${m}`)){order('RIDE Pay',a,m,'Berhasil');success('Pembayaran berhasil',`${money(a)} dibayar ke ${m}.`,'RIDE PAY')}return}
      if(e.target.closest('#doTransfer')){const to=qs('#transferTo')?.value.trim(),a=Number(qs('#transferAmount')?.value||0);if(!to||a<1000)return toast('Lengkapi penerima dan nominal.');if(charge(a,`Transfer ke ${to}`)){order('RIDE Transfer',a,to,'Berhasil');success('Transfer berhasil',`${money(a)} terkirim ke ${to}.`,'RIDE WALLET')}return}
      if(e.target.closest('#doRequest')){const a=Number(qs('#requestAmount')?.value||0);if(a<1000)return toast('Masukkan nominal.');const code=`RIDE-${Math.random().toString(36).slice(2,8).toUpperCase()}`;return openSheet('Permintaan dibuat','RIDE WALLET',`<div class="result-state success"><div class="result-icon">↙</div><h3>${money(a)}</h3><p>Bagikan kode ini ke teman.</p><div class="request-code">${code}</div><button class="super-primary" data-copy-text="${code}">Salin kode</button></div>`)}
      if(e.target.closest('#doBill')){const t=qs('#billType')?.value,id=qs('#billCustomer')?.value.trim(),a=Number(qs('#billAmount')?.value||0);if(!id||a<1000)return toast('Lengkapi data tagihan.');if(charge(a,`${t} · ${id}`)){order('RIDE Tagihan',a,`${t} · ${id}`,'Berhasil');success('Tagihan terbayar',`${t} senilai ${money(a)} berhasil dibayar.`,'RIDE TAGIHAN')}return}
      if(e.target.closest('#buyTransit')){const a=Number(qs('#buyTransit')?.dataset.price||18000),f=qs('#transitFrom')?.value,t=qs('#transitTo')?.value;if(charge(a,`Transit · ${f} → ${t}`)){order('RIDE Transit',a,`${f} → ${t}`,'Tiket aktif');success('Perjalanan transit siap',`Tiket demo ${f} ke ${t} sudah dibuat.`,'RIDE TRANSIT')}return}
      if(e.target.closest('#bookBox')){const p=qs('#boxPickup')?.value.trim(),d=qs('#boxDest')?.value.trim(),b=qs('#bookBox'),a=Number(b?.dataset.price||0),v=b?.dataset.truck||'Pickup';if(!p||!d)return toast('Lengkapi alamat.');if(charge(a,`RIDE Box · ${v}`)){order('RIDE Box',a,`${p} → ${d}`,'Driver dicari');success('Armada sedang dicari',`${v} untuk rute ${p} ke ${d} masuk antrean demo.`,'RIDE BOX')}return}
      if(e.target.closest('#bookShop')){const i=qs('#shopItems')?.value.trim(),s=qs('#shopStore')?.value.trim(),a=18000;if(!i||!s)return toast('Isi barang dan toko.');if(charge(a,`RIDE Shop · ${s}`)){order('RIDE Shop',a,`${s} · ${i.slice(0,35)}`,'Shopper dicari');success('Titip beli dibuat',`Shopper demo sedang dicari untuk ${s}.`,'RIDE SHOP')}return}
      if(e.target.closest('#doSchedule')){const t=qs('#scheduleTime')?.value,v=qs('#scheduleType')?.value,d=qs('#scheduleDest')?.value.trim(),a=5000;if(!t||!d)return toast('Lengkapi jadwal dan tujuan.');if(charge(a,`Reservasi · ${v}`)){order(v,a,`${d} · ${new Date(t).toLocaleString('id-ID')}`,'Terjadwal');success('Perjalanan dijadwalkan',`${v} akan disiapkan pada ${new Date(t).toLocaleString('id-ID')}.`,'RIDE RESERVE')}return}
      if(e.target.closest('#choosePremium')){closeSheet();existing('car');return setTimeout(()=>toast('Pilih tier Prioritas untuk pengalaman premium.'),180)}if(e.target.closest('#subscribePlus')){const b=qs('#subscribePlus'),a=Number(b?.dataset.price||29000),p=b?.dataset.plan||'Bulanan';if(charge(a,`RIDE Plus ${p}`)){localStorage.setItem('ride_plus_active','1');order('RIDE Plus',a,`Membership ${p}`,'Aktif');success('RIDE Plus aktif',`Membership ${p} demo berhasil diaktifkan.`,'RIDE PLUS')}return}if(e.target.closest('#successOrders')){closeSheet();return window.RIDE2?.openOrders?.()}if(e.target.closest('#saveSafetyContact')){localStorage.setItem('ride_safety_contact',qs('#safetyContact')?.value.trim()||'');return toast('Kontak tepercaya disimpan.')}if(e.target.closest('#shareTrip'))return toast('Tautan perjalanan demo siap dibagikan.');if(e.target.closest('#emergencyHelp'))return toast('Mode demo: tidak melakukan panggilan nyata.');if(e.target.closest('#audioProtect'))return toast('Perekaman proteksi demo diaktifkan.');if(e.target.closest('#insuranceInfo'))return toast('Proteksi perjalanan demo aktif.');if(e.target.closest('#openSupportChat'))return openSheet('Chat bantuan','RIDE SUPPORT','<div class="chat-demo"><div class="chat-bubble agent">Halo! Ada yang bisa kami bantu terkait perjalanan atau transaksi?</div><div class="chat-compose"><input placeholder="Tulis pesan"><button>➤</button></div></div>');if(e.target.closest('#merchantOnboarding'))return openSheet('Daftar usaha','RIDE MERCHANT','<div class="flow-card"><label>Nama usaha</label><input placeholder="Nama usaha"><label>Kategori</label><select><option>Makanan & minuman</option><option>Retail</option><option>Jasa</option></select><label>Nomor HP</label><input placeholder="08xxxxxxxxxx"><button class="super-primary" data-onboard>Kirim pendaftaran demo</button></div>');if(e.target.closest('#driverOnboarding'))return openSheet('Daftar mitra driver','RIDE PARTNER','<div class="flow-card"><label>Nama lengkap</label><input placeholder="Nama"><label>Nomor HP</label><input placeholder="08xxxxxxxxxx"><label>Kendaraan</label><select><option>Motor</option><option>Mobil</option></select><button class="super-primary" data-onboard>Kirim pendaftaran demo</button></div>');if(e.target.closest('[data-onboard]'))return success('Pendaftaran diterima','Data demo masuk antrean verifikasi partner.','PARTNER RIDE');if(e.target.closest('#launchAds'))return success('Campaign aktif','Campaign iklan demo berhasil dibuat.','RIDE ADS');if(e.target.closest('#posClear')){if(qs('#posCharge'))qs('#posCharge').dataset.total='0';if(qs('.pos-display h3'))qs('.pos-display h3').textContent=money(0);return}if(e.target.closest('#posCharge')){const a=Number(qs('#posCharge')?.dataset.total||0);if(!a)return toast('Tambahkan item.');order('RIDE POS',a,'Transaksi kasir demo','Berhasil');return success('Transaksi tersimpan',`${money(a)} dicatat sebagai transaksi POS demo.`,'RIDE POS')}
    },true);
    qsa('[data-super-filter]').forEach(b=>b.addEventListener('click',()=>{qsa('[data-super-filter]').forEach(x=>x.classList.toggle('active',x===b));renderHub(b.dataset.superFilter,qs('#serviceSearch')?.value||'')}));qs('#serviceSearch')?.addEventListener('input',e=>renderHub(qs('[data-super-filter].active')?.dataset.superFilter||'all',e.target.value));document.addEventListener('input',e=>{if(e.target.id==='payAmount'&&qs('#doPay'))qs('#doPay').textContent=`Bayar ${money(e.target.value)}`;if(e.target.id==='sheetServiceSearch'){const q=e.target.value.toLowerCase();qsa('.sheet-service-grid button').forEach(b=>b.hidden=q&&!b.textContent.toLowerCase().includes(q))}});window.addEventListener('focus',sync)}
  window.RIDESuper={openService:service,openAllServices:allServices,syncHome:sync};mount();
})();